/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jobdesk_admin;

import java.awt.Component;
import java.awt.Container;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.DateFormat;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.PatternSyntaxException;

import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Userpc
 */
public class frm_job_mon extends javax.swing.JFrame {

    private Crud_Job dat;
    private String username;
    private String idhps;
    private boolean cedit=false;
    private Date tgledit;
    private String jobnum;
    private String bulantahun;
    
    private int isilst=0;
    
    private  UtilJob tgl=new UtilJob();
    /**
     * Creates new form frm_job_mon
     */
    public frm_job_mon(String username) {

        this.username = username;
        initComponents();
        try {

            //hide cari berdasarkan Date_creation kga kepake
            dt_cari_creation.setVisible(false);
            jLabel13.setVisible(false);
            
            
            dat = new Crud_Job();
            dat.readRecPIC();

            txt_tahun.setEditor(new JSpinner.NumberEditor(txt_tahun,"#"));
            
            txt_tahun.setValue(Integer.parseInt(tgl.GetDate("tahun")));
            
            cmb_cari_bulan.setSelectedItem(tgl.ConvBulan(Integer.parseInt(tgl.GetDate("bulan"))));
            
           
            //cetak init perbulan
            txt_tahun1.setEditor(new JSpinner.NumberEditor(txt_tahun,"#"));
            
            txt_tahun1.setValue(Integer.parseInt(tgl.GetDate("tahun")));
            
            cmb_cari_bulan1.setSelectedItem(tgl.ConvBulan(Integer.parseInt(tgl.GetDate("bulan"))));
            
            
//            txt_tahun_cetak.setEditor(new JSpinner.NumberEditor(txt_tahun_cetak,"#"));
//            
//            txt_tahun_cetak.setValue(Integer.parseInt(tgl.GetDate("tahun")));
            
            
            dat = new Crud_Job();
            dat.readRec_selesai(tgl.GetDate("tahun")+"-"+tgl.GetDate("bulan"));
            
            bulantahun=tgl.GetDate("tahun")+"-"+tgl.GetDate("bulan");
            
            
           // bulantahun=txt_tahun.getValue()+"-"+tgl.GetAngkaBulan(cmb_cari_bulan.getSelectedIndex());
            
            System.out.println("tesss:"+bulantahun);
            
            
            
            tbl_users.setModel(dat.modelselesai);
           
          
            dat = new Crud_Job();
            dat.readRec();
            
             dat = new Crud_Job();
            dat.readRec1();
            
            lbl_aprove.setText(Crud_Job.apv);
            lbl_selesai.setText(Crud_Job.fin);
             
            
        } catch (Exception ex) {
            Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
        }

        
     //   refreshtbl();
        
     //   refreshtblxs();
        
        txt_username.setText(username);
        
        // addMouseListenerRecrusively(lbl_tgl_cur);

     UtilJob tgl=new UtilJob();
             lbl_tgl_activ.setText("Job List Di bulan : "+ tgl.GetNamabulan(tgl.GetDate("bulan")) + " / "+  tgl.GetDate("full"));
        

    }

//    private void addMouseListenerRecrusively(Container container){
//
//   for (Component component:container.getComponents()){
//     if (component instanceof Container)
//        addMouseListenerRecrusively((Container) component); 
//   }
//
//   container.addMouseListener(new java.awt.event.MouseAdapter() {
//        public void mouseClicked(java.awt.event.MouseEvent evt) {
//            
//            if(evt.getClickCount()==2){
//              int response = JOptionPane.showConfirmDialog(null, "Apakah Akan di hapus Pekerjaan di Tgl  ?", "Konfirmasi",
//                   JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
//            }
//            }
//    });
//
//}
    public frm_job_mon() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup_mnu = new javax.swing.JPopupMenu();
        mnu_edit = new javax.swing.JMenuItem();
        mnu_delete = new javax.swing.JMenuItem();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_users = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lbl_aprove = new javax.swing.JLabel();
        lbl_selesai = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        lbl_job_desc = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        lbl_user_list = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbl_pic = new javax.swing.JLabel();
        lbl_req = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbl_target = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbl_finish = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        lbl_remark = new javax.swing.JTextArea();
        lbl_priorty = new javax.swing.JLabel();
        ck_aprove = new javax.swing.JCheckBox();
        ck_selesai = new javax.swing.JCheckBox();
        bt_cetak1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bt_cetak_pertgl = new javax.swing.JButton();
        bt_cetak = new javax.swing.JButton();
        bt_refresh = new javax.swing.JButton();
        dt_cari_creation = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        txt_cari_desc = new javax.swing.JTextField();
        bt_cetak_perbulan = new javax.swing.JButton();
        dt_cetak_pertgl = new com.toedter.calendar.JDateChooser();
        cmb_cari_bulan1 = new javax.swing.JComboBox();
        txt_tahun1 = new javax.swing.JSpinner();
        lbl_tgl_activ = new javax.swing.JLabel();
        cmb_cari_bulan = new javax.swing.JComboBox();
        txt_tahun = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_pwd_lama = new javax.swing.JPasswordField();
        txt_username = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_pwd_baru = new javax.swing.JPasswordField();
        bt_save2 = new javax.swing.JButton();

        mnu_edit.setText("Edit");
        mnu_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_editActionPerformed(evt);
            }
        });
        popup_mnu.add(mnu_edit);

        mnu_delete.setText("Delete");
        mnu_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnu_deleteMouseClicked(evt);
            }
        });
        mnu_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_deleteActionPerformed(evt);
            }
        });
        popup_mnu.add(mnu_delete);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane2.setName(""); // NOI18N

        tbl_users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl_usersMouseReleased(evt);
            }
        });
        jScrollPane5.setViewportView(tbl_users);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(jTable2);

        lbl_aprove.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_aprove.setForeground(new java.awt.Color(0, 204, 204));
        lbl_aprove.setText("s");

        lbl_selesai.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_selesai.setForeground(new java.awt.Color(0, 204, 204));
        lbl_selesai.setText("s");

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_job_desc.setEditable(false);
        lbl_job_desc.setColumns(20);
        lbl_job_desc.setLineWrap(true);
        lbl_job_desc.setRows(5);
        jScrollPane6.setViewportView(lbl_job_desc);

        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Job Description");

        lbl_user_list.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_user_list.setText("User Name :");

        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("Pic");

        lbl_pic.setText(" ");
        lbl_pic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_req.setText(" ");
        lbl_req.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("Request");

        lbl_target.setText(" ");
        lbl_target.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setText("Target");

        jLabel20.setForeground(new java.awt.Color(0, 102, 102));
        jLabel20.setText("Finish");

        lbl_finish.setText(" ");
        lbl_finish.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel21.setForeground(new java.awt.Color(0, 102, 102));
        jLabel21.setText("Priorty Number");

        jLabel22.setForeground(new java.awt.Color(0, 102, 102));
        jLabel22.setText("Remark / Status");

        lbl_remark.setEditable(false);
        lbl_remark.setColumns(20);
        lbl_remark.setLineWrap(true);
        lbl_remark.setRows(5);
        lbl_remark.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbl_remarkKeyPressed(evt);
            }
        });
        jScrollPane7.setViewportView(lbl_remark);

        lbl_priorty.setText(" ");
        lbl_priorty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ck_aprove.setText("Aprove");
        ck_aprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_aproveActionPerformed(evt);
            }
        });

        ck_selesai.setText("Selesai");
        ck_selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_selesaiActionPerformed(evt);
            }
        });

        bt_cetak1.setText("Cetak Data ");
        bt_cetak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cetak1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_user_list, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_pic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_cetak1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_req, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_target, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_finish, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_priorty, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(ck_aprove)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ck_selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane7))
                                .addContainerGap())))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbl_user_list)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl_target))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl_req))))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_finish)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_pic))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_priorty)
                                    .addComponent(ck_aprove)
                                    .addComponent(ck_selesai)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_cetak1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 51));
        jLabel17.setText("Belum Aprove");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 51));
        jLabel18.setText("Belum Selesai");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Cari Data"));

        bt_cetak_pertgl.setText("Cetak Per Tgl");
        bt_cetak_pertgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cetak_pertglActionPerformed(evt);
            }
        });

        bt_cetak.setText("Cetak Semua");
        bt_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cetakActionPerformed(evt);
            }
        });

        bt_refresh.setText("Refresh");
        bt_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_refreshActionPerformed(evt);
            }
        });

        dt_cari_creation.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dt_cari_creationPropertyChange(evt);
            }
        });

        jLabel13.setText("Date Creation");

        jLabel12.setText("Status Selesai");

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("Selesai (ok)");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("Belum Selesai (no)");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("Aprove (ok)");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jLabel14.setText("Status Aprove");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Belum Aprove (no)");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jLabel23.setText("Job Description");

        txt_cari_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cari_descActionPerformed(evt);
            }
        });
        txt_cari_desc.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txt_cari_descPropertyChange(evt);
            }
        });
        txt_cari_desc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cari_descKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cari_descKeyReleased(evt);
            }
        });

        bt_cetak_perbulan.setText("Cetak Per Bulan");
        bt_cetak_perbulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cetak_perbulanActionPerformed(evt);
            }
        });

        cmb_cari_bulan1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        cmb_cari_bulan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_cari_bulan1ActionPerformed(evt);
            }
        });

        txt_tahun1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txt_tahun1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cari_desc))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton3)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 1, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dt_cari_creation, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(bt_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_cetak_pertgl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_cetak_perbulan, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(dt_cetak_pertgl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_cetak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cmb_cari_bulan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tahun1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bt_cetak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_cetak_pertgl)
                        .addGap(5, 5, 5)
                        .addComponent(dt_cetak_pertgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_cetak_perbulan)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton4)
                                    .addComponent(bt_refresh)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dt_cari_creation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txt_cari_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_cari_bulan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tahun1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_tgl_activ.setText(" ");

        cmb_cari_bulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        cmb_cari_bulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_cari_bulanActionPerformed(evt);
            }
        });

        txt_tahun.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txt_tahunStateChanged(evt);
            }
        });

        jLabel1.setText("Filter Data Berdasarkan Bulan dan Tahun");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_tgl_activ, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_aprove, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(lbl_selesai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmb_cari_bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_tahun))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_aprove, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(lbl_selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_tgl_activ)
                            .addComponent(cmb_cari_bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Job Activities", jPanel1);

        jLabel9.setText("User");

        jLabel10.setText("Password Lama");

        txt_username.setEditable(false);

        jLabel11.setText("Password Baru");

        bt_save2.setText("Save");
        bt_save2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_save2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_save2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pwd_lama, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pwd_baru, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(903, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pwd_lama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pwd_baru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_save2)
                .addContainerGap(468, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Ubah Password", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txt_username.setText(username);
    }//GEN-LAST:event_formWindowOpened

    
    
    
private void CekGantiPass(){
    try {
            // TODO add your handling code here:

           // StrPr c = new StrPr();
            
            
            dat = new Crud_Job();
            
            dat.Cek(txt_username.getText());
            
            
            
            if (Crud_Job.usm.equals(txt_username.getText()) && Crud_Job.psm.equals(txt_pwd_lama.getText())) {
                dat = new Crud_Job();
                dat.updateusrRec(txt_username.getText(), txt_pwd_baru.getText());
                  
                
            } else {
                JOptionPane.showMessageDialog(null, "Password atau User Salah!");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }    
    
    
 private void showPopupMenu(MouseEvent e) {
   popup_mnu.show(this, e.getX(), e.getY());
}
    
    private void mnu_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnu_deleteMouseClicked
    }//GEN-LAST:event_mnu_deleteMouseClicked

    private void mnu_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_deleteActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Apakah Akan di hapus Pekerjaan di Tgl " + idhps + " ?", "Konfirmasi",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {

            try {
                // TODO add your handling code here:
                dat = new Crud_Job();
                dat.DelRec(idhps);
                refreshtbl();
            } catch (Exception ex) {
                Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_mnu_deleteActionPerformed

    private void mnu_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_editActionPerformed
        // TODO add your handling code here:
     
        

    }//GEN-LAST:event_mnu_editActionPerformed

    private void getUser(){
     int row = tbl_users.getSelectedRow();

        if (row != -1) {
        lbl_user_list.setText(tbl_users.getModel().getValueAt(row, 1).toString());
         try {
             dat=new Crud_Job();
             
             System.out.println("Trace:"+txt_tahun.getValue()+"-"+tgl.GetAngkaBulan(cmb_cari_bulan.getSelectedIndex()));
             dat.readJobactiv(lbl_user_list.getText(),txt_tahun.getValue()+"-"+tgl.GetAngkaBulan(cmb_cari_bulan.getSelectedIndex()));
             jTable2.setModel(dat.model);
             
             isilst=dat.model.getRowCount();
             
         } catch (Exception ex) {
             Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
        } 
        
    }
    
    private void refUser(){
        try {
            dat=new Crud_Job();
             dat.readJobactiv(lbl_user_list.getText(),bulantahun);
             jTable2.setModel(dat.model);
        } catch (Exception ex) {
            Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    
    }
    
    private void getTblActiv(){
         int row = jTable2.getSelectedRow();

        if (row == -1) {
            // No row selected
        } else {

           
               
                
                lbl_job_desc.setText(jTable2.getModel().getValueAt(row, 1).toString());
                lbl_pic.setText(jTable2.getModel().getValueAt(row, 2).toString());
                lbl_req.setText(jTable2.getModel().getValueAt(row, 3).toString());
                lbl_target.setText(jTable2.getModel().getValueAt(row, 4).toString());
                lbl_finish.setText(jTable2.getModel().getValueAt(row, 5).toString());
                lbl_priorty.setText(jTable2.getModel().getValueAt(row, 6).toString());
                lbl_remark.setText(jTable2.getModel().getValueAt(row, 7).toString());
              
               ck_aprove.setSelected(setsel(jTable2.getModel().getValueAt(row, 8).toString()));
               ck_selesai.setSelected(setsel(jTable2.getModel().getValueAt(row, 9).toString()));
           jobnum=jTable2.getModel().getValueAt(row, 7).toString();
        }
    
    }
    
    private boolean setsel(String val){
    boolean f=false;
    
    if (val.equals("ok")){
    
    f=true;
    }
    
    return f;
    
    }
    
   
    
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMousePressed

    private void bt_save2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_save2ActionPerformed
        // TODO add your handling code here:
        if(!txt_pwd_baru.getText().isEmpty()&&!txt_pwd_lama.getText().isEmpty()){
            CekGantiPass();
        }
        else{

        }
    }//GEN-LAST:event_bt_save2ActionPerformed

    private void txt_tahunStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txt_tahunStateChanged
        // TODO add your handling code here:
        bulantahun=txt_tahun.getValue()+"-"+tgl.GetAngkaBulan(cmb_cari_bulan.getSelectedIndex());
        cari_filter();
    }//GEN-LAST:event_txt_tahunStateChanged

    private void cmb_cari_bulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_cari_bulanActionPerformed
        // TODO add your handling code here:
        bulantahun=txt_tahun.getValue()+"-"+tgl.GetAngkaBulan(cmb_cari_bulan.getSelectedIndex());
        cari_filter();
    }//GEN-LAST:event_cmb_cari_bulanActionPerformed

    private void bt_cetak_perbulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cetak_perbulanActionPerformed
        // TODO add your handling code here:
      //    if(dt_cetak_perbulan.getDate()!=null)  {
            try {
                dat = new Crud_Job();

                dat.CetakPerBulan(txt_tahun1.getValue()+"-"+tgl.GetAngkaBulan(cmb_cari_bulan1.getSelectedIndex()));

            } catch (Exception e2) {
                // TODO Auto-generated catch block
                e2.printStackTrace();
            }
//        }
//        else{
//
//            JOptionPane.showMessageDialog(null, "Tanggal Pencarian Kosong!");
//        }
    }//GEN-LAST:event_bt_cetak_perbulanActionPerformed

    private void txt_cari_descKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cari_descKeyReleased
        // TODO add your handling code here:

        filtertbl();

    }//GEN-LAST:event_txt_cari_descKeyReleased

    private void txt_cari_descKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cari_descKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_cari_descKeyPressed

    private void txt_cari_descPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txt_cari_descPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_cari_descPropertyChange

    private void txt_cari_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cari_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cari_descActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            dat=new Crud_Job();
            dat.readRecStat("no", 1,lbl_user_list.getText(),bulantahun);
            jTable2.setModel(dat.model);
            
             isilst=dat.model.getRowCount();

        } catch (Exception ex) {
            Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            dat=new Crud_Job();
            dat.readRecStat("ok", 1,lbl_user_list.getText(),bulantahun);
            jTable2.setModel(dat.model);

             isilst=dat.model.getRowCount();
        } catch (Exception ex) {
            Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        try {
            // TODO add your handling code here:
            dat=new Crud_Job();
            dat.readRecStat("no", 0,lbl_user_list.getText(),bulantahun);
            jTable2.setModel(dat.model);
             isilst=dat.model.getRowCount();
        } catch (Exception ex) {
            Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            dat=new Crud_Job();
            dat.readRecStat("ok", 0,lbl_user_list.getText(),bulantahun);
            jTable2.setModel(dat.model);
            
             isilst=dat.model.getRowCount();
            

        } catch (Exception ex) {
            Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void dt_cari_creationPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dt_cari_creationPropertyChange
        // TODO add your handling code here:
        if (dt_cari_creation.getDate() != null) {
            refreshtblx();
            // dt_cari_creation.setDate(null);
            //System.out.print("K filter");
        }
    }//GEN-LAST:event_dt_cari_creationPropertyChange

    private void bt_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_refreshActionPerformed

        dt_cari_creation.setDate(null);

        refUser();
        reftbl();
    }//GEN-LAST:event_bt_refreshActionPerformed

    private void bt_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cetakActionPerformed
        // TODO add your handling code here:

        //if(dt_cari_creation.getDate()!=null)  {
            try {
                dat = new Crud_Job();

                
                
                dat.CetakAll(lbl_selesai.getText());

            } catch (Exception e2) {
                // TODO Auto-generated catch block
                e2.printStackTrace();
            }
            //}
        //   else{

            //   JOptionPane.showMessageDialog(null, "Tanggal Pencarian Kosong!");
            //  }
    }//GEN-LAST:event_bt_cetakActionPerformed

    private void bt_cetak_pertglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cetak_pertglActionPerformed
        // TODO add your handling code here:

        // convertToDateF

        if(dt_cetak_pertgl.getDate()!=null)  {
            try {
                dat = new Crud_Job();

                dat.CetakPerTgl(convertToDateF(dt_cetak_pertgl.getDate()));

            } catch (Exception e2) {
                // TODO Auto-generated catch block
                e2.printStackTrace();
            }
        }
        else{

            JOptionPane.showMessageDialog(null, "Tanggal Pencarian Kosong!");
        }
    }//GEN-LAST:event_bt_cetak_pertglActionPerformed

    private void ck_selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_selesaiActionPerformed
        // TODO add your handling code here:
        // ck_aprove.setSelected(false);

        //begin
        int row = jTable2.getSelectedRow();

        try {

            dat = new Crud_Job();

            if (row != -1) {
                if(dat.CekRecaprove(jTable2.getModel().getValueAt(row, 11).toString()).equals("ok")){

                    int response = JOptionPane.showConfirmDialog(null, "Apakah Akan di Set Selesai Pekerjaan ini " + lbl_job_desc.getText() + " ?", "Konfirmasi",
                        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

                    if (response == JOptionPane.YES_OPTION) {

                        dat = new Crud_Job();
                        dat.updateAprove(jTable2.getModel().getValueAt(row, 11).toString(),"ok",1);
                        getUser();

                        //refresh status
                        dt_cari_creation.setDate(null);
                        reftbl();

                    }//end edit
                }

                else{

                    JOptionPane.showMessageDialog(null,"Tidak bisa di Set Selesai karena Belum di Aprove");
                    ck_selesai.setSelected(false);

                }
                //end
            }
        } catch (Exception ex) {
            Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ck_selesaiActionPerformed

    private void ck_aproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_aproveActionPerformed
        // TODO add your handling code here:
        //  ck_selesai.setSelected(false);
        //System.out.println("Ck aprove");

        int response = JOptionPane.showConfirmDialog(null, "Apakah Akan di Aprove Pekerjaan ini " + lbl_job_desc.getText() + " ?", "Konfirmasi",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {

            int row = jTable2.getSelectedRow();

            if (row != -1) {

                try {
                    // TODO add your handling code here:
                    dat = new Crud_Job();
                    dat.updateAprove(jTable2.getModel().getValueAt(row, 11).toString(),"ok",0);
                    getUser();

                    //refresh status
                    dt_cari_creation.setDate(null);
                    reftbl();

                } catch (Exception ex) {
                    Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }

    }//GEN-LAST:event_ck_aproveActionPerformed

    private void lbl_remarkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_remarkKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_remarkKeyPressed

    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        // TODO add your handling code here:

        if(evt.getClickCount()==2){
            getTblActiv();
        }

    }//GEN-LAST:event_jTable2MousePressed

    private void tbl_usersMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_usersMouseReleased
        // TODO add your handling code here:

        if(evt.getClickCount()==2){
            getUser();
        }
        
    }//GEN-LAST:event_tbl_usersMouseReleased

    private void cmb_cari_bulan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_cari_bulan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_cari_bulan1ActionPerformed

    private void txt_tahun1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txt_tahun1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tahun1StateChanged

    private void bt_cetak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cetak1ActionPerformed
        // TODO add your handling code here:
        System.out.println(isilst);
        
        if(isilst>=1){
           JOptionPane.showMessageDialog(null, "Ok sip!");
        }
        else{
         JOptionPane.showMessageDialog(null, "Data User List JObs Kosong!");
        }
    }//GEN-LAST:event_bt_cetak1ActionPerformed

    private void filtertbl(){
        try {
            dat = new Crud_Job();
          
//           final TableRowSorter<TableModel> sorter =
//                 new TableRowSorter<TableModel>(dat.model);
//      
//            
//         System.out.println("jml :"+dat.model.getRowCount());
//         
         if (txt_cari_desc.getText()!=null) {
             
              dat.FilterJobactiv(lbl_user_list.getText(),txt_cari_desc.getText(),bulantahun);
              jTable2.setModel(dat.modelfilter);
              
              isilst=dat.modelfilter.getRowCount();
              
//               jTable2.setRowSorter(sorter);
//               sorter.setRowFilter(null);
//             } else {
//               try {
//                     jTable2.setRowSorter(sorter);
//                 sorter.setRowFilter(
//                     RowFilter.regexFilter(txt_cari_desc.getText()));
//               } catch (PatternSyntaxException pse) {
//                 System.err.println("Bad regex pattern");
//               }
             }
         else{
         
          dat.readJobactiv(lbl_user_list.getText(),bulantahun);
              jTable2.setModel(dat.model);
              
              isilst=dat.model.getRowCount();
         }
         
            
        } catch (Exception ex) {
            Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }
    
    private Date ConvStrToDate(String tgl) {


        DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        Date tglt = null;
        try {
            tglt = df.parse(tgl);

        } catch (ParseException e) {
            e.printStackTrace();
        }

        return tglt;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_job_mon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_job_mon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_job_mon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_job_mon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_job_mon().setVisible(true);
            }
        });

    }

    public void refreshtbl() {

        try {
            dat = new Crud_Job();

//            dat.readRec(convertToDateF(lbl_tgl_cur.getDate()));

            dat.readRec_selesai();
            
             lbl_aprove.setText(Crud_Job.apv);
             lbl_selesai.setText(Crud_Job.fin);
            
        } catch (Exception e2) {
            // TODO Auto-generated catch block
            e2.printStackTrace();
        }

    //    jTable1.setModel(dat.model);
        
       // tbl_users.setModel(dat.modelselesai);
        
    }

    
    public void refreshtblx() {

        try {
            dat = new Crud_Job();

            dat.readRec(convertToDateF(dt_cari_creation.getDate()),lbl_user_list.getText());

        } catch (Exception e2) {
            // TODO Auto-generated catch block
            e2.printStackTrace();
        }

        jTable2.setModel(dat.model);
    }

    public void refreshtblxs() {

        try {
            dat = new Crud_Job();

            dat.readRec();

        } catch (Exception e2) {
            // TODO Auto-generated catch block
            e2.printStackTrace();
        }

        jTable2.setModel(dat.model);
    }

    
    private Date Getcurdate() {

        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");

        Date date = new Date();

        //dateFormat.format(date)

        return date;
    }

    private String convertToDateF(Date receivedDate) throws ParseException {
//HH:mm:ss
        
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");

        String strDate = formatter.format(receivedDate);

        return strDate;
    }

    private String convertToDateE(Date receivedDate) throws ParseException {

        // SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");

        String strDate = formatter.format(receivedDate);

        return strDate;
    }
    
    private Date convertToDateEx(String receivedDate) throws ParseException {

        //SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");

        Date strDate = formatter.parse(receivedDate);

        return strDate;
    }
    
    
    private String convertToDate(Date receivedDate) throws ParseException {

        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");

        String strDate = formatter.format(receivedDate);

        return strDate;
    }

   

    private void cari_filter(){
        try {
            dat = new Crud_Job();
            
          
            
           // int i=cmb_cari_bulan.getSelectedIndex()+1;
            
             dat.readRec_selesai(txt_tahun.getValue()+"-"+tgl.GetAngkaBulan(cmb_cari_bulan.getSelectedIndex()));
               tbl_users.setModel(dat.modelselesai);
               
               System.out.println(txt_tahun.getValue()+"-"+tgl.GetAngkaBulan(cmb_cari_bulan.getSelectedIndex()));
        } catch (Exception ex) {
            Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
        }
         
      
    
    }
    
    private void reftbl(){
        try {
            dat = new Crud_Job();
            dat.readRec_selesai(tgl.GetDate("tahun")+"-"+tgl.GetDate("bulan"));
            
            
            tbl_users.setModel(dat.modelselesai);
           
          
            dat = new Crud_Job();
            dat.readRec();
            
             dat = new Crud_Job();
            dat.readRec1();
            
            lbl_aprove.setText(Crud_Job.apv);
            lbl_selesai.setText(Crud_Job.fin);
        } catch (Exception ex) {
            Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
    }
    private void cls() {



        for (Component c : jPanel1.getComponents()) {


            if (c instanceof JTextComponent) {
                ((JTextComponent) c).setText("");
            }
        }

//        sp_priorty.setValue(0);

        jobnum="";
        
//        dt_req.setDate(null);
//        dt_target.setDate(null);
//        txt_job_desc.setText("");
//        txt_remark.setText("");

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cetak;
    private javax.swing.JButton bt_cetak1;
    private javax.swing.JButton bt_cetak_perbulan;
    private javax.swing.JButton bt_cetak_pertgl;
    private javax.swing.JButton bt_refresh;
    private javax.swing.JButton bt_save2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox ck_aprove;
    private javax.swing.JCheckBox ck_selesai;
    private javax.swing.JComboBox cmb_cari_bulan;
    private javax.swing.JComboBox cmb_cari_bulan1;
    private com.toedter.calendar.JDateChooser dt_cari_creation;
    private com.toedter.calendar.JDateChooser dt_cetak_pertgl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl_aprove;
    private javax.swing.JLabel lbl_finish;
    private javax.swing.JTextArea lbl_job_desc;
    private javax.swing.JLabel lbl_pic;
    private javax.swing.JLabel lbl_priorty;
    private javax.swing.JTextArea lbl_remark;
    private javax.swing.JLabel lbl_req;
    private javax.swing.JLabel lbl_selesai;
    private javax.swing.JLabel lbl_target;
    private javax.swing.JLabel lbl_tgl_activ;
    private javax.swing.JLabel lbl_user_list;
    private javax.swing.JMenuItem mnu_delete;
    private javax.swing.JMenuItem mnu_edit;
    private javax.swing.JPopupMenu popup_mnu;
    private javax.swing.JTable tbl_users;
    private javax.swing.JTextField txt_cari_desc;
    private javax.swing.JPasswordField txt_pwd_baru;
    private javax.swing.JPasswordField txt_pwd_lama;
    private javax.swing.JSpinner txt_tahun;
    private javax.swing.JSpinner txt_tahun1;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
